const servicesDataList = [
  {
    id: "Addiction-Treatment",
    name: "Addiction Treatment",
    image: "/images/services/Substance_Abuse_Addiction.jpg",
    imageAlt:
      "Professional addiction treatment therapy session with counselor and patient",
    id_sub: "Comprehensive support for recovery and healing",
    title1: "Break free from addiction with Tinka Health's compassionate care",
    title1Des:
      "Addiction is a complex disease that affects your brain, behavior, and relationships. Whether you're struggling with substance use, behavioral addictions, or both, recovery is possible. At Tinka Health, we provide evidence-based addiction treatment that addresses not just the addiction itself, but the underlying factors that contribute to it.",
    btnText: "Start Recovery",
    title2: "Is addiction controlling your life and relationships?",
    title2Des:
      "Addiction often starts as a way to cope with pain, stress, or trauma, but it quickly becomes a cycle that's difficult to break. You might feel ashamed, isolated, or hopeless about your situation. Addiction doesn't just affect you - it impacts everyone who cares about you. Here's how addiction can take over your life:",
    title2List: [
      "Loss of control over your substance use or behaviors despite negative consequences",
      "Damaged relationships with family, friends, and romantic partners",
      "Problems at work or school, including decreased performance or attendance",
      "Financial difficulties due to spending money on substances or addictive behaviors",
      "Legal problems or risky behaviors that put you or others in danger",
      "Physical health complications and mental health issues like depression or anxiety",
      "Isolation and withdrawal from activities and people you once enjoyed",
      "Feelings of shame, guilt, and hopelessness about your ability to change",
    ],
    title3: "Tinka Health's goals for your recovery journey:",
    title3Des:
      "Recovery from addiction is a journey, not a destination. At Tinka Health, we believe that with the right support, anyone can overcome addiction and build a fulfilling life in recovery. We take a comprehensive approach that addresses the physical, emotional, and psychological aspects of addiction. Tinka Health will help you:",
    title3List: [
      "Develop a personalized treatment plan that addresses your specific addiction and underlying issues",
      "Learn healthy coping strategies to manage triggers, cravings, and stressful situations",
      "Address any co-occurring mental health conditions like depression, anxiety, or trauma",
      "Build a strong support network and repair damaged relationships when possible",
      "Understand the root causes of your addiction and develop insight into your patterns",
      "Create a relapse prevention plan and develop tools for long-term recovery",
      "Rebuild your life with purpose, meaning, and healthy habits that support your sobriety",
    ],
  },
  {
    id: "Adult-Psychiatry",
    name: "Adult Psychiatry",
    image: "/images/services/Mental_Health.jpg",
    imageAlt: "Adult psychiatry consultation with mental health professional",
    id_sub: "Comprehensive psychiatric care for adults",
    title1: "Expert psychiatric care tailored for adult mental health needs",
    title1Des:
      "Adult psychiatry focuses on the diagnosis, treatment, and prevention of mental health disorders in adults. At Tinka Health, our psychiatric services combine medication management with therapeutic support to provide comprehensive care that addresses both the biological and psychological aspects of mental health conditions.",
    btnText: "Get Psychiatric Care",
    title2: "Are you struggling with complex mental health challenges?",
    title2Des:
      "Many adults experience mental health conditions that require specialized psychiatric care. These conditions can significantly impact your daily life, relationships, and overall well-being. Without proper treatment, psychiatric conditions can lead to:",
    title2List: [
      "Persistent symptoms that interfere with work or personal relationships",
      "Difficulty managing emotions, thoughts, or behaviors",
      "Physical symptoms related to mental health conditions",
      "Increased risk of substance use or other harmful coping mechanisms",
      "Social isolation and withdrawal from important activities",
      "Decreased quality of life and overall functioning",
    ],
    title3: "How Tinka Health's Adult Psychiatry Services Help",
    title3Des:
      "Our adult psychiatry services provide comprehensive evaluation and treatment for a wide range of mental health conditions. Our experienced psychiatrists work closely with you to develop personalized treatment plans. Here's how we support your mental health:",
    title3List: [
      "Comprehensive psychiatric evaluations to accurately diagnose mental health conditions",
      "Medication management and monitoring to optimize treatment effectiveness",
      "Integration of therapy and medication for the best possible outcomes",
      "Treatment of complex conditions including bipolar disorder, schizophrenia, and severe depression",
      "Ongoing support and adjustment of treatment plans as needed",
      "Collaboration with other healthcare providers for holistic care",
      "Education about your condition and treatment options",
    ],
  },
  {
    id: "Agoraphobia",
    name: "Agoraphobia",
    image: "/images/services/Agoraphobia.jpg",
    imageAlt:
      "Peaceful outdoor scene representing overcoming agoraphobia through therapy",
    id_sub: "Overcome fear of open spaces and regain your freedom",
    title1: "Conquer agoraphobia with expert guidance and support",
    title1Des:
      "Agoraphobia is more than just fear of open spaces - it's an anxiety disorder that can make you feel trapped in your own life. You might avoid places or situations where escape seems difficult or help unavailable. At Tinka Health, we understand how limiting agoraphobia can be, and we're here to help you gradually reclaim your independence and confidence.",
    btnText: "Reclaim My Freedom",
    title2: "Is agoraphobia limiting your life?",
    title2Des:
      "Agoraphobia can develop gradually or suddenly, often following a panic attack in a specific location. It can significantly impact your daily life and relationships, leading to:",
    title2List: [
      "Avoidance of crowded places, public transportation, or being alone outside",
      "Difficulty leaving your home or safe spaces",
      "Panic attacks when faced with feared situations",
      "Dependence on others for daily activities like shopping or errands",
      "Social isolation and strained relationships",
      "Impact on work or school attendance and performance",
      "Physical symptoms like rapid heartbeat, sweating, or dizziness",
    ],
    title3: "How Tinka Health Helps You Overcome Agoraphobia",
    title3Des:
      "Our approach to treating agoraphobia combines evidence-based techniques with gradual, supportive exposure. We'll work at your pace to help you:",
    title3List: [
      "Understand the connection between thoughts, feelings, and avoidance behaviors",
      "Learn relaxation and breathing techniques to manage panic and anxiety",
      "Gradually expose yourself to feared situations in a controlled, supportive way",
      "Challenge and change negative thoughts about safety and danger",
      "Develop coping strategies for managing anxiety in various situations",
      "Build confidence and independence in your daily activities",
      "Create a long-term plan for maintaining your progress",
    ],
  },
  {
    id: "Alzheimers-Disease",
    name: "Alzheimer's Disease",
    image: "/images/services/Alzheimer's-Disease.jpg",
    imageAlt:
      "Elderly care and support for Alzheimer's disease patients and families",
    id_sub: "Support for patients and families facing cognitive decline",
    title1: "Comprehensive care for Alzheimer's disease and dementia",
    title1Des:
      "Alzheimer's disease affects not just the individual diagnosed, but their entire family and support network. At Tinka Health, we provide compassionate care and support for both patients in early stages and their families, helping navigate the emotional, practical, and psychological challenges of this condition.",
    btnText: "Get Support",
    title2: "Are you or your loved one facing Alzheimer's challenges?",
    title2Des:
      "Alzheimer's disease brings unique challenges that can feel overwhelming. Early intervention and support can make a significant difference in quality of life for everyone involved:",
    title2List: [
      "Memory loss and confusion that interferes with daily activities",
      "Changes in mood, personality, or behavior",
      "Difficulty with problem-solving and decision-making",
      "Challenges with communication and language",
      "Family stress and caregiver burnout",
      "Anxiety and depression related to the diagnosis",
      "Planning for future care needs and legal matters",
    ],
    title3: "Tinka Health's Approach to Alzheimer's Support",
    title3Des:
      "We provide comprehensive support that addresses the psychological and emotional aspects of Alzheimer's disease for both patients and families:",
    title3List: [
      "Individual counseling for patients dealing with diagnosis and early-stage symptoms",
      "Family therapy to improve communication and coping strategies",
      "Support groups for caregivers and family members",
      "Grief counseling for the losses associated with cognitive decline",
      "Stress management techniques for caregivers",
      "Coordination with healthcare providers for comprehensive care",
      "Resources and education about the disease and available support services",
    ],
  },
  {
    id: "Anger-Management",
    name: "Anger Management",
    image: "/images/services/Mental_Health.jpg",
    imageAlt:
      "Calm anger management therapy session with professional counselor",
    id_sub: "Learn healthy ways to express and control anger",
    title1:
      "Transform your relationship with anger through professional guidance",
    title1Des:
      "Anger is a natural emotion, but when it becomes overwhelming or destructive, it can damage relationships and negatively impact your life. Tinka Health's anger management services help you understand your triggers, develop healthy coping strategies, and learn to express anger in constructive ways.",
    btnText: "Manage My Anger",
    title2: "Is anger causing problems in your life?",
    title2Des:
      "Uncontrolled anger can have serious consequences for your relationships, career, and overall well-being. Many people struggle with anger management, and without proper support, it can lead to:",
    title2List: [
      "Damaged relationships with family, friends, and colleagues",
      "Problems at work or school, including potential job loss",
      "Legal issues or conflicts that could have been avoided",
      "Physical health problems related to chronic stress and anger",
      "Feelings of guilt, shame, and regret after angry outbursts",
      "Social isolation and loss of important relationships",
    ],
    title3: "Tinka Health's Approach to Anger Management",
    title3Des:
      "Our anger management program is designed to help you gain control over your anger responses and develop healthier ways to cope with frustration and stress. Through evidence-based techniques, you'll learn to:",
    title3List: [
      "Identify your anger triggers and early warning signs",
      "Develop better communication skills to express your needs without aggression",
      "Practice conflict resolution strategies that protect your relationships",
      "Build emotional regulation skills that help you stay calm under pressure",
      "Address any underlying mental health conditions that might contribute to anger issues",
    ],
  },
  {
    id: "Antidepressants",
    name: "Antidepressants",
    image: "/images/services/Antidepressants.jpg",
    imageAlt:
      "Medication management for depression treatment with healthcare professional",
    id_sub: "Expert medication management and monitoring",
    title1: "Professional antidepressant medication management",
    title1Des:
      "Finding the right antidepressant medication can be a crucial part of your mental health treatment. At Tinka Health, our psychiatric professionals provide expert medication management, ensuring you receive the most effective treatment with minimal side effects, while monitoring your progress closely.",
    btnText: "Get Medication Support",
    title2: "Are you considering or currently taking antidepressants?",
    title2Des:
      "Antidepressant medication can be highly effective, but finding the right medication and dosage requires professional guidance and ongoing monitoring:",
    title2List: [
      "Uncertainty about which medication might work best for you",
      "Concerns about side effects or interactions with other medications",
      "Questions about how long treatment should continue",
      "Need for dosage adjustments or medication changes",
      "Monitoring for effectiveness and side effects",
      "Support during the initial weeks when medications are taking effect",
    ],
    title3: "Tinka Health's Medication Management Approach",
    title3Des:
      "Our comprehensive medication management ensures you receive safe, effective treatment tailored to your specific needs:",
    title3List: [
      "Thorough psychiatric evaluation to determine the best medication options",
      "Regular monitoring appointments to assess effectiveness and side effects",
      "Gradual dosage adjustments based on your response and tolerance",
      "Education about your medication, including benefits and potential side effects",
      "Coordination with your primary care physician and other healthcare providers",
      "Support during medication transitions or discontinuation when appropriate",
      "Integration of medication management with therapy for optimal outcomes",
    ],
  },
  {
    id: "Anxiety",
    name: "Anxiety",
    image: "/images/services/Anxiety.jpg",
    imageAlt:
      "Anxiety therapy session helping patient overcome worry and stress",
    id_sub: "Find relief from worry, fear, and anxious thoughts",
    title1: "Overcome anxiety with personalized treatment and support",
    title1Des:
      "Anxiety is one of the most common mental health challenges, affecting millions of people. Whether you're dealing with general worry, specific fears, or physical symptoms of anxiety, Tinka Health provides comprehensive treatment to help you find relief and regain control of your life.",
    btnText: "Get Anxiety Relief",
    title2: "Is anxiety affecting your daily life?",
    title2Des:
      "Anxiety can manifest in many different ways and impact every aspect of your life. Common signs and effects include:",
    title2List: [
      "Persistent worry about everyday situations",
      "Physical symptoms like rapid heartbeat, sweating, or trembling",
      "Difficulty concentrating or making decisions",
      "Sleep problems or restlessness",
      "Avoidance of situations that trigger anxiety",
      "Fatigue from constant worry and tension",
      "Impact on relationships, work, or school performance",
    ],
    title3: "How Tinka Health Treats Anxiety",
    title3Des:
      "Our approach to anxiety treatment is comprehensive and personalized, using evidence-based techniques to help you:",
    title3List: [
      "Identify and understand your specific anxiety triggers",
      "Learn practical coping strategies and relaxation techniques",
      "Challenge and change anxious thought patterns",
      "Gradually face feared situations in a safe, controlled way",
      "Develop long-term strategies for managing anxiety",
      "Address any underlying issues contributing to your anxiety",
      "Build confidence and resilience for lasting recovery",
    ],
  },
  {
    id: "Attention-Deficit-Hyperactivity-Disorder",
    name: "Attention Deficit Hyperactivity Disorder",
    image: "/images/services/Attention Deficit-Hyperactivity-Disorder.jpg",
    imageAlt: "ADHD treatment and therapy for focus and attention improvement",
    id_sub: "Comprehensive ADHD evaluation and treatment",
    title1: "Expert ADHD diagnosis and management for all ages",
    title1Des:
      "ADHD affects millions of children and adults, impacting focus, impulse control, and daily functioning. At Tinka Health, we provide comprehensive ADHD evaluations, accurate diagnosis, and personalized treatment plans that may include therapy, medication management, and behavioral strategies to help you or your loved one thrive.",
    btnText: "Get ADHD Support",
    title2: "Is ADHD affecting your or your child's life?",
    title2Des:
      "ADHD symptoms can significantly impact academic, work, and social functioning. Common challenges include:",
    title2List: [
      "Difficulty focusing on tasks or following through on responsibilities",
      "Impulsive behavior that leads to problems at school, work, or in relationships",
      "Hyperactivity or restlessness that interferes with daily activities",
      "Problems with organization, time management, and planning",
      "Academic or work performance below potential",
      "Social difficulties and strained relationships",
      "Low self-esteem and frustration with ongoing challenges",
    ],
    title3: "Tinka Health's Comprehensive ADHD Treatment",
    title3Des:
      "Our approach to ADHD treatment is thorough and individualized, designed to help you or your child succeed:",
    title3List: [
      "Comprehensive evaluation and accurate diagnosis of ADHD",
      "Medication management with careful monitoring and adjustments",
      "Behavioral therapy and coaching to develop coping strategies",
      "Family education and support to improve home and school environments",
      "Coordination with schools and teachers for academic accommodations",
      "Social skills training and peer relationship support",
      "Long-term planning for academic and career success",
    ],
  },
  {
    id: "Autism-Spectrum-Disorder",
    name: "Autism Spectrum Disorder",
    image: "/images/services/Autism_Spectrum_Disorder.jpg",
    imageAlt:
      "Autism spectrum disorder therapy and behavioral support services",
    id_sub: "Support for individuals and families navigating autism",
    title1: "Comprehensive autism spectrum disorder support and services",
    title1Des:
      "Autism Spectrum Disorder (ASD) affects individuals differently, but all deserve understanding, support, and the opportunity to reach their full potential. At Tinka Health, we provide specialized services for individuals with autism and their families, focusing on building strengths, addressing challenges, and improving quality of life.",
    btnText: "Get Autism Support",
    title2: "Are you seeking support for autism spectrum challenges?",
    title2Des:
      "Autism spectrum disorder can present various challenges that affect daily life, relationships, and development:",
    title2List: [
      "Difficulty with social communication and interaction",
      "Repetitive behaviors or intense interests in specific topics",
      "Challenges with transitions and changes in routine",
      "Sensory sensitivities that affect daily activities",
      "Academic or workplace accommodations needs",
      "Family stress and need for support and resources",
      "Building independence and life skills",
    ],
    title3: "How Tinka Health Supports Individuals with Autism",
    title3Des:
      "Our autism support services are designed to meet the unique needs of each individual and their family:",
    title3List: [
      "Comprehensive autism evaluations and diagnosis",
      "Individual therapy focused on social skills and communication",
      "Family support and education about autism spectrum disorders",
      "Behavioral interventions to address challenging behaviors",
      "Social skills groups and peer interaction opportunities",
      "Coordination with schools and other service providers",
      "Transition planning for adolescents and young adults",
    ],
  },
  {
    id: "Bereavement",
    name: "Bereavement",
    image: "/images/services/Bereavement.jpg",
    imageAlt: "Grief counseling and bereavement therapy support services",
    id_sub: "Compassionate support through loss and grief",
    title1: "Healing support for those experiencing loss and grief",
    title1Des:
      "Losing someone important to you is one of life's most difficult experiences. Grief is a natural response to loss, but it can feel overwhelming and isolating. At Tinka Health, we provide compassionate bereavement counseling to help you navigate your grief journey and find ways to honor your loved one while rebuilding your life.",
    btnText: "Find Grief Support",
    title2: "Are you struggling with the pain of loss?",
    title2Des:
      "Grief affects everyone differently and can impact all aspects of your life. Common experiences include:",
    title2List: [
      "Overwhelming sadness, anger, or numbness",
      "Difficulty accepting the reality of the loss",
      "Physical symptoms like fatigue, sleep problems, or loss of appetite",
      "Trouble concentrating on daily tasks or making decisions",
      "Feeling disconnected from others or socially isolated",
      "Guilt or regret about things said or left unsaid",
      "Difficulty finding meaning or purpose after the loss",
    ],
    title3: "Tinka Health's Approach to Bereavement Support",
    title3Des:
      "Our bereavement counseling provides a safe space to process your grief and begin healing:",
    title3List: [
      "Individual counseling to process your unique grief experience",
      "Support groups with others who have experienced similar losses",
      "Help understanding the grief process and what to expect",
      "Coping strategies for managing difficult emotions and memories",
      "Guidance on how to maintain connections with your deceased loved one",
      "Support for family members and loved ones also affected by the loss",
      "Assistance with anniversary dates, holidays, and other difficult times",
    ],
  },
  {
    id: "Bipolar-Disorder",
    name: "Bipolar Disorder",
    id_sub: "Manage mood swings and live with stability",
    title1: "Get support for managing bipolar disorder with Tinka Health",
    title1Des:
      "If you are living with bipolar disorder, you might feel like a slave to your moods and emotions. At some points, you feel depressed, unmotivated, and withdrawn. However, at other times, you feel elated, impulsive, restless, agitated, and full of self-confidence. This emotional instability can greatly impact your life but Tinka Health is here to help you stabilize your moods and make healthier choices.",
    btnText: "Let's Do It",
    title2: "Does bipolar disorder make your moods unpredictable?",
    title2Des:
      "Bipolar disorder is characterized by mood swings between hypomania, mania, and major depressive episodes, with types ranging from Bipolar I (severe mania sometimes requiring hospitalization) to Bipolar II (major depressive episodes with less severe hypomania) and cyclothymia (frequent, less intense mood shifts). Manic episodes may bring heightened energy, irritability, and impulsive behaviors like overspending or risk-taking, which, despite the temporary high, often lead to serious consequences including:",
    title2List: [
      "Emotional crashes after manic episodes",
      "Impulsive actions that might result in harm or regret",
      "Substance use as a coping mechanism",
      "Struggles with relationships",
      "Fluctuations in sleep, appetite, and energy",
      "Poor self-image or identity crises",
    ],
    title3: "Tinka Health's approach to therapy for bipolar disorder",
    title3Des:
      "Bipolar disorder affects everyone differently, and Tinka Health understands that your experience is unique. Our goal is to help you regulate your mood and regain control of your mental health. Here's how Tinka Health can support you:",
    title3List: [
      "Explore treatment options, including lifestyle changes, talk therapy, and potentially medication, to help you manage mood swings.",
      "Reduce impulsive or risky behaviors that could impact your relationships, health, finances, or work.",
      "Address depressive feelings, social withdrawal, and thoughts of self-harm.",
      "Decrease substance use during mood episodes and find healthier coping mechanisms.",
      "Understand how bipolar disorder affects your life and develop strategies to navigate periods of mania and depression effectively.",
    ],
  },
  {
    id: "Depression",
    name: "Depression",
    image: "/images/services/Depression.jpg",
    imageAlt:
      "Depression therapy and treatment with mental health professional",
    id_sub: "Find hope and healing from depression",
    title1: "Overcome depression with compassionate, professional support",
    title1Des:
      "Depression is more than just feeling sad or going through a rough patch. It's a serious mental health condition that affects how you think, feel, and handle daily activities. At Tinka Health, we understand that depression can feel overwhelming and isolating, but with the right support and treatment, recovery is possible.",
    btnText: "Start Healing",
    title2: "Is depression affecting your daily life?",
    title2Des:
      "Depression can manifest in various ways and significantly impact every aspect of your life. If you're experiencing persistent sadness, loss of interest in activities, or other symptoms of depression, you may be dealing with:",
    title2List: [
      "Persistent feelings of sadness, emptiness, or hopelessness",
      "Loss of interest or pleasure in activities you once enjoyed",
      "Significant changes in appetite or weight",
      "Sleep disturbances, including insomnia or oversleeping",
      "Fatigue and decreased energy levels",
      "Difficulty concentrating, making decisions, or remembering things",
      "Feelings of worthlessness or excessive guilt",
      "Thoughts of death or suicide",
    ],
    title3: "How Tinka Health Helps You Overcome Depression",
    title3Des:
      "Our approach to treating depression is comprehensive and personalized, combining evidence-based therapies with compassionate support. We'll work together to understand the root causes of your depression and develop effective strategies for healing. Here's how we support your recovery:",
    title3List: [
      "Identify and challenge negative thought patterns that contribute to depression",
      "Develop healthy coping strategies for managing difficult emotions",
      "Address any underlying trauma or life stressors that may be contributing to your depression",
      "Build a support network and improve your relationships",
      "Establish healthy routines and lifestyle habits that support mental wellness",
      "Work on building self-esteem and rediscovering your sense of purpose",
      "Create a personalized relapse prevention plan for long-term recovery",
    ],
  },
  {
    id: "Eating-Disorders",
    name: "Eating Disorders",
    image: "/images/services/Eating_Disorders.jpg",
    imageAlt: "Eating disorder treatment and nutritional therapy support",
    id_sub: "Specialized treatment for eating disorders and body image",
    title1: "Comprehensive care for eating disorders and recovery",
    title1Des:
      "Eating disorders are serious mental health conditions that affect your relationship with food, body image, and overall well-being. They can impact anyone regardless of age, gender, or background. At Tinka Health, we provide specialized, compassionate care for various eating disorders, supporting you on your journey to recovery.",
    btnText: "Start Recovery",
    title2: "Are you struggling with an eating disorder?",
    title2Des:
      "Eating disorders can control your thoughts, emotions, and behaviors around food and body image, leading to serious physical and mental health consequences:",
    title2List: [
      "Obsessive thoughts about food, weight, and body shape",
      "Restrictive eating, binge eating, or purging behaviors",
      "Social isolation and withdrawal from family and friends",
      "Physical health complications from disordered eating behaviors",
      "Depression, anxiety, and mood swings related to eating patterns",
      "Perfectionism and unrealistic standards for yourself",
      "Feeling out of control around food or eating",
    ],
    title3: "Tinka Health's Eating Disorder Treatment Approach",
    title3Des:
      "Our comprehensive treatment addresses the psychological, behavioral, and physical aspects of eating disorders:",
    title3List: [
      "Individual therapy focused on eating disorder recovery and underlying issues",
      "Nutritional counseling and meal planning support",
      "Body image therapy and self-acceptance work",
      "Family therapy to improve support systems and communication",
      "Group therapy with others in eating disorder recovery",
      "Medical monitoring and coordination with healthcare providers",
      "Relapse prevention and long-term recovery planning",
    ],
  },
  {
    id: "Mental-Health",
    name: "Mental Health",
    image: "/images/services/Mental_Health.jpg",
    imageAlt: "Comprehensive mental health therapy and wellness services",
    id_sub: "Comprehensive mental health care and support",
    title1: "Complete mental health services for overall well-being",
    title1Des:
      "Mental health is essential to your overall well-being, affecting how you think, feel, and act in daily life. Whether you're facing specific challenges or simply want to maintain good mental health, Tinka Health provides comprehensive services to support your psychological wellness and personal growth.",
    btnText: "Improve Mental Health",
    title2: "Are you prioritizing your mental health and well-being?",
    title2Des:
      "Mental health affects every aspect of your life, and maintaining good mental health requires attention and care:",
    title2List: [
      "Stress management and coping with life's challenges",
      "Relationship difficulties and communication problems",
      "Work-life balance and career-related stress",
      "Life transitions and major changes",
      "Self-esteem and confidence issues",
      "Personal growth and self-improvement goals",
      "Preventive mental health care and wellness maintenance",
    ],
    title3: "Tinka Health's Comprehensive Mental Health Services",
    title3Des:
      "Our mental health services address a wide range of concerns and support your overall psychological well-being:",
    title3List: [
      "Individual therapy for personal growth and problem-solving",
      "Couples and family therapy to improve relationships",
      "Stress management and mindfulness training",
      "Life coaching and goal-setting support",
      "Mental health screening and preventive care",
      "Crisis intervention and emergency mental health support",
      "Wellness planning and long-term mental health maintenance",
    ],
  },
  {
    id: "Medical-Marijuana-Certification",
    name: "Medical Marijuana Certification",
    image: "/images/services/Medical_Marijuana_Certification.jpg",
    imageAlt:
      "Medical marijuana certification consultation with healthcare provider",
    id_sub: "Professional medical cannabis evaluations and certifications",
    title1: "Get certified for medical marijuana with expert evaluation",
    title1Des:
      "Medical marijuana can be an effective treatment option for various medical and mental health conditions. At Tinka Health, our qualified physicians provide thorough evaluations to determine if medical cannabis is appropriate for your condition and help you obtain legal certification in compliance with state regulations.",
    btnText: "Get Certified",
    title2: "Could medical marijuana help with your condition?",
    title2Des:
      "Medical marijuana has been shown to be effective for various conditions. Our certification process ensures you receive proper medical oversight:",
    title2List: [
      "Chronic pain and inflammatory conditions",
      "PTSD and anxiety-related disorders",
      "Depression and mood disorders",
      "Epilepsy and seizure disorders",
      "Cancer and chemotherapy-related symptoms",
      "Glaucoma and other qualifying medical conditions",
      "Sleep disorders and insomnia",
    ],
    title3: "Tinka Health's Medical Marijuana Certification Process",
    title3Des:
      "Our comprehensive evaluation ensures you receive appropriate care and legal protection:",
    title3List: [
      "Thorough medical history review and physical examination",
      "Assessment of your qualifying medical condition",
      "Discussion of medical marijuana as a treatment option",
      "Education about dosing, strains, and delivery methods",
      "Certification documentation and state registration assistance",
      "Ongoing monitoring and follow-up care",
      "Coordination with your existing healthcare providers",
    ],
  },
  {
    id: "Medication-Management",
    name: "Medication Management",
    image: "/images/services/Medication_management.jpg",
    imageAlt: "Psychiatric medication management and monitoring services",
    id_sub: "Expert psychiatric medication oversight and optimization",
    title1:
      "Optimize your mental health with professional medication management",
    title1Des:
      "Proper medication management is crucial for mental health treatment success. At Tinka Health, our psychiatric professionals provide comprehensive medication management services, ensuring you receive the most effective treatment with minimal side effects through careful monitoring and adjustments.",
    btnText: "Optimize My Medications",
    title2: "Are you getting the most from your psychiatric medications?",
    title2Des:
      "Effective medication management requires ongoing professional oversight to ensure optimal outcomes:",
    title2List: [
      "Questions about medication effectiveness or side effects",
      "Need for dosage adjustments or medication changes",
      "Concerns about drug interactions with other medications",
      "Difficulty with medication adherence or complex regimens",
      "Transitioning between different psychiatric medications",
      "Managing multiple mental health conditions with various medications",
      "Long-term medication monitoring and safety assessments",
    ],
    title3: "Tinka Health's Comprehensive Medication Management",
    title3Des:
      "Our systematic approach ensures safe, effective psychiatric medication treatment:",
    title3List: [
      "Comprehensive psychiatric evaluation and medication review",
      "Regular monitoring appointments to assess effectiveness and side effects",
      "Careful dosage adjustments based on your response and tolerance",
      "Drug interaction screening and safety assessments",
      "Patient education about medications and expected outcomes",
      "Coordination with primary care physicians and other specialists",
      "Long-term treatment planning and optimization strategies",
    ],
  },
  {
    id: "Obsessive-Compulsive-Disorder",
    name: "Obsessive Compulsive Disorder",
    image: "/images/services/Obsessive_Compulsive_Disorder.jpg",
    imageAlt: "OCD therapy and treatment for obsessive compulsive behaviors",
    id_sub: "Break free from obsessions and compulsions",
    title1: "Overcome OCD with specialized treatment and support",
    title1Des:
      "Obsessive-Compulsive Disorder (OCD) involves unwanted, intrusive thoughts (obsessions) and repetitive behaviors or mental acts (compulsions) that you feel compelled to perform. OCD can be exhausting and interfere significantly with your daily life. At Tinka Health, we provide specialized treatment to help you break free from OCD cycles.",
    btnText: "Beat OCD",
    title2: "Is OCD controlling your daily life?",
    title2Des:
      "OCD can consume hours of your day and create significant distress. Common experiences include:",
    title2List: [
      "Intrusive, unwanted thoughts that cause anxiety and distress",
      "Repetitive behaviors or mental rituals you feel compelled to perform",
      "Time-consuming routines that interfere with daily activities",
      "Avoidance of situations that trigger obsessions",
      "Significant distress when unable to perform compulsions",
      "Impact on relationships, work, or school performance",
      "Feeling ashamed or embarrassed about your thoughts and behaviors",
    ],
    title3: "Tinka Health's Specialized OCD Treatment",
    title3Des:
      "Our evidence-based approach to OCD treatment helps you regain control of your life:",
    title3List: [
      "Exposure and Response Prevention (ERP) therapy - the gold standard for OCD treatment",
      "Cognitive Behavioral Therapy specifically adapted for OCD",
      "Medication management when appropriate",
      "Family education and support to reduce accommodation behaviors",
      "Gradual exposure exercises to reduce anxiety and compulsions",
      "Relapse prevention and long-term management strategies",
      "Support groups with others who understand OCD challenges",
    ],
  },
  {
    id: "Opioid-Medication-Assistant-Treatment",
    name: "Opioid Medication Assistant Treatment",
    image: "/images/services/Opioid_medication_assistant_treatment.jpg",
    imageAlt: "Opioid medication assisted treatment and recovery services",
    id_sub: "Comprehensive medication-assisted treatment for opioid addiction",
    title1: "Overcome opioid addiction with medication-assisted treatment",
    title1Des:
      "Opioid addiction is a serious medical condition that requires professional treatment. At Tinka Health, we provide medication-assisted treatment (MAT) that combines FDA-approved medications with counseling and behavioral therapies to treat opioid use disorders and support long-term recovery.",
    btnText: "Start MAT Treatment",
    title2: "Are you struggling with opioid addiction?",
    title2Des:
      "Opioid addiction affects millions of people and can have devastating consequences. Medication-assisted treatment has been proven effective for:",
    title2List: [
      "Prescription opioid addiction (pain medications, oxycodone, hydrocodone)",
      "Heroin addiction and illegal opioid use",
      "Fentanyl addiction and synthetic opioid dependence",
      "Reducing withdrawal symptoms and cravings",
      "Preventing overdose and reducing mortality risk",
      "Supporting long-term recovery and relapse prevention",
      "Improving overall quality of life and functioning",
    ],
    title3: "Tinka Health's Medication-Assisted Treatment Program",
    title3Des:
      "Our comprehensive MAT program combines medication with comprehensive support services:",
    title3List: [
      "Medical evaluation and assessment for appropriate MAT medications",
      "Prescription and monitoring of medications like buprenorphine or naltrexone",
      "Individual counseling and addiction therapy",
      "Group therapy and peer support programs",
      "Family counseling and education about opioid addiction",
      "Coordination with primary care providers and specialists",
      "Long-term recovery planning and aftercare support",
    ],
  },
  {
    id: "Panic-Disorder",
    name: "Panic Disorder",
    image: "/images/services/Panic_Disorder.jpg",
    imageAlt: "Panic disorder treatment and anxiety management therapy",
    id_sub: "Overcome panic attacks and regain control",
    title1: "Find relief from panic attacks with expert care",
    title1Des:
      "Panic disorder involves recurrent, unexpected panic attacks and persistent worry about having more attacks. These intense episodes of fear can make you feel like you're losing control or having a heart attack. At Tinka Health, we help you understand panic attacks, reduce their frequency, and regain confidence in your daily life.",
    btnText: "Stop Panic Attacks",
    title2: "Are panic attacks disrupting your life?",
    title2Des:
      "Panic attacks can be terrifying and lead to significant life changes as you try to avoid situations where they might occur:",
    title2List: [
      "Sudden, intense episodes of fear with physical symptoms like rapid heartbeat",
      "Fear of having another panic attack (anticipatory anxiety)",
      "Avoidance of places or situations where panic attacks have occurred",
      "Physical symptoms like sweating, trembling, shortness of breath, or dizziness",
      "Feeling like you're going crazy, losing control, or dying during attacks",
      "Emergency room visits due to panic attack symptoms",
      "Significant impact on work, social activities, or daily functioning",
    ],
    title3: "Tinka Health's Panic Disorder Treatment",
    title3Des:
      "Our comprehensive approach helps you overcome panic attacks and reduce anxiety:",
    title3List: [
      "Education about panic attacks and how they work in your body",
      "Breathing techniques and relaxation strategies for managing symptoms",
      "Cognitive therapy to address catastrophic thinking patterns",
      "Gradual exposure to feared situations in a safe, controlled way",
      "Medication management if appropriate",
      "Lifestyle changes to reduce overall anxiety and stress",
      "Long-term strategies for preventing future panic attacks",
    ],
  },
  {
    id: "Post-Traumatic-Stress-Disorder",
    name: "Post Traumatic Stress Disorder",
    image: "/images/services/Post_Traumatic_Stress_Disorder.jpg",
    imageAlt: "PTSD therapy and trauma recovery treatment services",
    id_sub: "Heal from trauma with specialized PTSD treatment",
    title1: "Recovery from trauma and PTSD with expert care",
    title1Des:
      "Post-Traumatic Stress Disorder (PTSD) can develop after experiencing or witnessing a traumatic event. It affects your ability to feel safe and can significantly impact your daily life, relationships, and well-being. At Tinka Health, we provide trauma-informed care to help you process your experiences and reclaim your life.",
    btnText: "Heal from Trauma",
    title2: "Are you struggling with the effects of trauma?",
    title2Des:
      "PTSD can develop after various traumatic experiences and significantly impact your life:",
    title2List: [
      "Intrusive memories, flashbacks, or nightmares about the traumatic event",
      "Avoidance of people, places, or situations that remind you of the trauma",
      "Negative changes in thoughts and mood, including feelings of hopelessness",
      "Hypervigilance and being easily startled or frightened",
      "Sleep problems, difficulty concentrating, or irritability",
      "Emotional numbness or detachment from loved ones",
      "Self-destructive behavior or substance use as coping mechanisms",
    ],
    title3: "Tinka Health's PTSD Treatment Approach",
    title3Des:
      "Our trauma-informed treatment helps you process traumatic experiences and develop healthy coping strategies:",
    title3List: [
      "Evidence-based therapies like EMDR, CPT, and Prolonged Exposure",
      "Individual trauma therapy in a safe, supportive environment",
      "Medication management for PTSD symptoms when appropriate",
      "Group therapy with other trauma survivors",
      "Family therapy to improve relationships and support systems",
      "Mindfulness and grounding techniques for managing triggers",
      "Long-term recovery planning and resilience building",
    ],
  },
  {
    id: "Schizophrenia",
    name: "Schizophrenia",
    image: "/images/services/Schizophrenia.jpg",
    imageAlt: "Schizophrenia treatment and psychiatric care services",
    id_sub: "Comprehensive care for schizophrenia and psychotic disorders",
    title1: "Expert treatment for schizophrenia and recovery support",
    title1Des:
      "Schizophrenia is a complex mental health condition that affects thinking, perception, emotions, and behavior. With proper treatment and support, people with schizophrenia can lead fulfilling lives. At Tinka Health, we provide comprehensive care that combines medication management, therapy, and psychosocial support.",
    btnText: "Get Comprehensive Care",
    title2: "Are you or your loved one living with schizophrenia?",
    title2Des:
      "Schizophrenia can significantly impact daily functioning, but with proper treatment, symptoms can be managed effectively:",
    title2List: [
      "Hallucinations (hearing or seeing things others don't)",
      "Delusions (false beliefs that seem real to you)",
      "Disorganized thinking and speech patterns",
      "Difficulty with concentration and memory",
      "Social withdrawal and reduced emotional expression",
      "Challenges with daily living activities",
      "Impact on work, school, and relationships",
    ],
    title3: "Tinka Health's Schizophrenia Treatment Approach",
    title3Des:
      "Our comprehensive treatment addresses all aspects of schizophrenia care:",
    title3List: [
      "Psychiatric evaluation and accurate diagnosis",
      "Medication management with regular monitoring and adjustments",
      "Individual therapy to address symptoms and improve coping",
      "Family education and support services",
      "Social skills training and rehabilitation services",
      "Crisis intervention and emergency support",
      "Long-term recovery planning and community integration",
    ],
  },
  {
    id: "Stress-Management",
    name: "Stress Management",
    image: "/images/services/Stress_management.jpg",
    imageAlt: "Stress management therapy and coping strategies training",
    id_sub: "Learn effective techniques to manage and reduce stress",
    title1: "Master stress management for better mental and physical health",
    title1Des:
      "Stress is a normal part of life, but chronic stress can take a serious toll on your mental and physical health. At Tinka Health, we help you develop effective stress management techniques that reduce your stress levels and improve your overall quality of life.",
    btnText: "Reduce My Stress",
    title2: "Is stress overwhelming your daily life?",
    title2Des:
      "Chronic stress can affect every aspect of your life and lead to serious health problems if not properly managed:",
    title2List: [
      "Physical symptoms like headaches, muscle tension, and fatigue",
      "Emotional symptoms including anxiety, irritability, and mood swings",
      "Sleep problems and changes in appetite",
      "Difficulty concentrating and making decisions",
      "Relationship problems and social withdrawal",
      "Increased risk of anxiety, depression, and other mental health issues",
      "Impact on work performance and daily functioning",
    ],
    title3: "Tinka Health's Stress Management Program",
    title3Des:
      "Our comprehensive stress management program teaches you practical skills to handle stress more effectively:",
    title3List: [
      "Identify your personal stress triggers and warning signs",
      "Learn relaxation techniques including deep breathing and progressive muscle relaxation",
      "Develop healthy coping strategies and problem-solving skills",
      "Practice mindfulness and meditation techniques",
      "Improve time management and organizational skills",
      "Build resilience and emotional regulation abilities",
      "Create a personalized stress management plan for ongoing wellness",
    ],
  },
  {
    id: "Substance-Abuse",
    name: "Substance Abuse",
    image: "/images/services/Substance_Abuse_Addiction.jpg",
    imageAlt: "Substance abuse treatment and addiction recovery services",
    id_sub: "Recovery-focused treatment for substance use disorders",
    title1: "Overcome substance abuse with compassionate, evidence-based care",
    title1Des:
      "Substance abuse affects millions of people and their families, but recovery is always possible. At Tinka Health, we provide comprehensive substance abuse treatment that addresses both the addiction and the underlying factors that contribute to it, supporting you on your journey to lasting recovery.",
    btnText: "Start Recovery Journey",
    title2: "Is substance abuse controlling your life?",
    title2Des:
      "Substance abuse can have devastating effects on your health, relationships, and overall quality of life:",
    title2List: [
      "Loss of control over substance use despite negative consequences",
      "Physical health problems and increased risk of overdose",
      "Mental health issues including depression and anxiety",
      "Damaged relationships with family and friends",
      "Problems at work or school, including potential job loss",
      "Financial difficulties and legal problems",
      "Social isolation and loss of interests and activities",
    ],
    title3: "Tinka Health's Substance Abuse Treatment Approach",
    title3Des:
      "Our evidence-based treatment program addresses all aspects of substance abuse recovery:",
    title3List: [
      "Comprehensive assessment and personalized treatment planning",
      "Individual therapy to address underlying causes of substance abuse",
      "Group therapy with others in recovery for peer support",
      "Family therapy to heal relationships and build support systems",
      "Relapse prevention planning and coping skills development",
      "Coordination with medical providers for detox and medical care when needed",
      "Long-term recovery support and aftercare planning",
    ],
  },
  {
    id: "Suboxone-Treatment",
    name: "Suboxone Treatment",
    image: "/images/services/Suboxone_treatment.jpg",
    imageAlt: "Suboxone treatment for opioid addiction recovery",
    id_sub:
      "Specialized Suboxone medication-assisted treatment for opioid addiction",
    title1: "Effective opioid addiction treatment with Suboxone",
    title1Des:
      "Suboxone is a highly effective medication-assisted treatment for opioid addiction that helps reduce withdrawal symptoms and cravings. At Tinka Health, our qualified providers offer comprehensive Suboxone treatment programs that combine medication with counseling and support services for lasting recovery.",
    btnText: "Start Suboxone Treatment",
    title2: "Is opioid addiction controlling your life?",
    title2Des:
      "Suboxone treatment can help you break free from opioid addiction and reclaim your life. Our program addresses:",
    title2List: [
      "Prescription opioid addiction (OxyContin, Percocet, Vicodin, etc.)",
      "Heroin addiction and street opioid dependence",
      "Severe withdrawal symptoms and cravings",
      "Multiple failed attempts at getting clean",
      "Fear of withdrawal and detox process",
      "Need for medical supervision during recovery",
      "Desire for outpatient treatment that allows you to maintain daily responsibilities",
    ],
    title3: "Tinka Health's Comprehensive Suboxone Program",
    title3Des:
      "Our Suboxone treatment program provides medical oversight and comprehensive support:",
    title3List: [
      "Medical evaluation and assessment for Suboxone candidacy",
      "Safe Suboxone induction and stabilization process",
      "Regular monitoring appointments and medication management",
      "Individual counseling and addiction therapy",
      "Group therapy and peer support groups",
      "Relapse prevention planning and coping skills training",
      "Gradual tapering and long-term recovery support when ready",
    ],
  },
  {
    id: "Grief-and-Loss",
    name: "Grief and Loss",
    image: "/images/services/Bereavement.jpg",
    imageAlt: "Grief and loss counseling therapy support services",
    id_sub: "Compassionate support through grief and loss",
    title1: "Navigate grief and loss with professional support",
    title1Des:
      "Losing someone or something important to you is one of life's most challenging experiences. Grief is a natural response to loss, but it can feel overwhelming and isolating. At Tinka Health, we provide compassionate grief counseling to help you process your emotions, honor your loss, and find healthy ways to move forward.",
    btnText: "Get Grief Support",
    title2: "Are you struggling with grief and loss?",
    title2Des:
      "Grief can affect every aspect of your life and manifest in many different ways:",
    title2List: [
      "Intense sadness, anger, or numbness following a significant loss",
      "Difficulty accepting the reality of your loss",
      "Feeling overwhelmed by emotions or unable to feel anything at all",
      "Changes in sleep patterns, appetite, or energy levels",
      "Difficulty concentrating or making decisions",
      "Social withdrawal and isolation from family and friends",
      "Physical symptoms like headaches, fatigue, or body aches",
      "Feeling guilty about moving on or experiencing moments of happiness",
    ],
    title3: "Tinka Health's Grief and Loss Support",
    title3Des:
      "Our compassionate approach to grief counseling helps you process your loss and find healthy ways to cope:",
    title3List: [
      "Individual grief counseling tailored to your unique loss experience",
      "Support groups with others who have experienced similar losses",
      "Help understanding the stages of grief and the healing process",
      "Coping strategies for managing difficult emotions and triggers",
      "Guidance on maintaining connections with your deceased loved one",
      "Support for complicated grief and traumatic loss situations",
      "Family counseling to improve communication during difficult times",
      "Long-term support as you navigate your grief journey",
    ],
  },
  {
    id: "Insomnia",
    name: "Insomnia",
    image: "/images/services/insomnia.jpg",
    imageAlt: "Insomnia treatment and sleep therapy services",
    id_sub: "Overcome sleep disorders and improve sleep quality",
    title1: "Restore healthy sleep patterns with professional treatment",
    title1Des:
      "Insomnia and sleep disorders can significantly impact your physical health, mental well-being, and daily functioning. At Tinka Health, we provide comprehensive treatment for sleep disorders, helping you develop healthy sleep habits and address underlying factors that may be affecting your rest.",
    btnText: "Improve My Sleep",
    title2: "Is insomnia affecting your quality of life?",
    title2Des:
      "Sleep disorders can have far-reaching effects on your health and daily functioning:",
    title2List: [
      "Difficulty falling asleep or staying asleep throughout the night",
      "Waking up feeling unrefreshed despite spending adequate time in bed",
      "Daytime fatigue, irritability, and difficulty concentrating",
      "Increased anxiety or depression related to sleep problems",
      "Physical health issues related to poor sleep quality",
      "Reliance on sleep medications or substances to fall asleep",
      "Impact on work performance, relationships, and daily activities",
      "Racing thoughts or worry that interfere with falling asleep",
    ],
    title3: "Tinka Health's Insomnia Treatment Approach",
    title3Des:
      "Our comprehensive approach addresses both the symptoms and underlying causes of sleep disorders:",
    title3List: [
      "Cognitive Behavioral Therapy for Insomnia (CBT-I) - the gold standard treatment",
      "Sleep hygiene education and environmental optimization",
      "Relaxation techniques and stress management strategies",
      "Assessment and treatment of underlying mental health conditions",
      "Medication management when appropriate and necessary",
      "Sleep schedule regulation and circadian rhythm support",
      "Addressing lifestyle factors that impact sleep quality",
      "Long-term maintenance strategies for healthy sleep patterns",
    ],
  },
];

export default servicesDataList;
