const servicesDataList = [
  {
    id: "Addiction-Treatment",
    name: "Addiction Treatment",
    id_sub: "Comprehensive support for recovery and healing",
    title1: "Break free from addiction with Tinka Health's compassionate care",
    title1Des:
      "Addiction is a complex disease that affects your brain, behavior, and relationships. Whether you're struggling with substance use, behavioral addictions, or both, recovery is possible. At Tinka Health, we provide evidence-based addiction treatment that addresses not just the addiction itself, but the underlying factors that contri    title3List: [
      "Persistent feelings of sadness, emptiness, or hopelessness",
      "Loss of interest or pleasure in activities you once enjoyed",
      "Changes in appetite, sleep patterns, or energy levels",
      "Difficulty concentrating, making decisions, or remembering things",
      "Feelings of worthlessness, guilt, or self-blame",
      "Physical symptoms like headaches or unexplained aches and pains",
      "Thoughts of death or suicide",
    ],
    title3: "How Tinka Health Helps You Overcome Depression",
    title3Des:
      "Our comprehensive approach to depression treatment combines evidence-based therapies with personalized care to help you find relief and regain hope:",
    title3List: [
      "Individual therapy using proven techniques like CBT and interpersonal therapy",
      "Medication management when appropriate, with careful monitoring",
      "Support groups to connect with others who understand your experience",
      "Lifestyle interventions including exercise, nutrition, and sleep hygiene",
      "Family therapy to improve relationships and support systems",
      "Crisis intervention and safety planning when needed",
      "Long-term relapse prevention and wellness planning",
    ],
  },
  {
    id: "Dual-Diagnosis",
    name: "Dual Diagnosis",
    id_sub: "Integrated treatment for addiction and mental health",
    title1: "Comprehensive care for co-occurring addiction and mental health disorders",
    title1Des:
      "When addiction and mental health conditions occur together, it's called dual diagnosis or co-occurring disorders. This complex situation requires specialized treatment that addresses both conditions simultaneously. At Tinka Health, we provide integrated care that treats your whole person, not just individual symptoms.",
    btnText: "Get Integrated Care",
    title2: "Are you struggling with both addiction and mental health issues?",
    title2Des:
      "Dual diagnosis is more common than many people realize. When mental health conditions and substance use disorders occur together, they can worsen each other if not properly treated:",
    title2List: [
      "Using substances to cope with depression, anxiety, or trauma symptoms",
      "Mental health symptoms worsening during addiction or recovery",
      "Difficulty determining which condition came first",
      "Previous treatment failures that only addressed one condition",
      "Increased risk of relapse without comprehensive care",
      "Complex medication management needs",
      "Feeling overwhelmed by multiple diagnoses and treatments",
    ],
    title3: "Tinka Health's Integrated Dual Diagnosis Treatment",
    title3Des:
      "Our comprehensive approach treats both conditions simultaneously for the best possible outcomes:",
    title3List: [
      "Comprehensive assessment to identify all co-occurring conditions",
      "Integrated treatment planning that addresses both addiction and mental health",
      "Medication management for complex psychiatric and addiction medicine needs",
      "Individual therapy that addresses trauma, depression, anxiety, and addiction",
      "Group therapy with others facing similar dual diagnosis challenges",
      "Family therapy and education about co-occurring disorders",
      "Relapse prevention planning that considers both mental health and addiction triggers",
    ],
  },
  {
    id: "Eating-Disorders",
    name: "Eating Disorders",
    id_sub: "Specialized treatment for eating disorders and body image",
    title1: "Comprehensive care for eating disorders and recovery",
    title1Des:
      "Eating disorders are serious mental health conditions that affect your relationship with food, body image, and overall well-being. They can impact anyone regardless of age, gender, or background. At Tinka Health, we provide specialized, compassionate care for various eating disorders, supporting you on your journey to recovery.",
    btnText: "Start Recovery",
    title2: "Are you struggling with an eating disorder?",
    title2Des:
      "Eating disorders can control your thoughts, emotions, and behaviors around food and body image, leading to serious physical and mental health consequences:",
    title2List: [
      "Obsessive thoughts about food, weight, and body shape",
      "Restrictive eating, binge eating, or purging behaviors",
      "Social isolation and withdrawal from family and friends",
      "Physical health complications from disordered eating behaviors",
      "Depression, anxiety, and mood swings related to eating patterns",
      "Perfectionism and unrealistic standards for yourself",
      "Feeling out of control around food or eating",
    ],
    title3: "Tinka Health's Eating Disorder Treatment Approach",
    title3Des:
      "Our comprehensive treatment addresses the psychological, behavioral, and physical aspects of eating disorders:",
    title3List: [
      "Individual therapy focused on eating disorder recovery and underlying issues",
      "Nutritional counseling and meal planning support",
      "Body image therapy and self-acceptance work",
      "Family therapy to improve support systems and communication",
      "Group therapy with others in eating disorder recovery",
      "Medical monitoring and coordination with healthcare providers",
      "Relapse prevention and long-term recovery planning",
    ],
  },
  {
    id: "Mental-Health",
    name: "Mental Health",
    id_sub: "Comprehensive mental health care and support",
    title1: "Complete mental health services for overall well-being",
    title1Des:
      "Mental health is essential to your overall well-being, affecting how you think, feel, and act in daily life. Whether you're facing specific challenges or simply want to maintain good mental health, Tinka Health provides comprehensive services to support your psychological wellness and personal growth.",
    btnText: "Improve Mental Health",
    title2: "Are you prioritizing your mental health and well-being?",
    title2Des:
      "Mental health affects every aspect of your life, and maintaining good mental health requires attention and care:",
    title2List: [
      "Stress management and coping with life's challenges",
      "Relationship difficulties and communication problems",
      "Work-life balance and career-related stress",
      "Life transitions and major changes",
      "Self-esteem and confidence issues",
      "Personal growth and self-improvement goals",
      "Preventive mental health care and wellness maintenance",
    ],
    title3: "Tinka Health's Comprehensive Mental Health Services",
    title3Des:
      "Our mental health services address a wide range of concerns and support your overall psychological well-being:",
    title3List: [
      "Individual therapy for personal growth and problem-solving",
      "Couples and family therapy to improve relationships",
      "Stress management and mindfulness training",
      "Life coaching and goal-setting support",
      "Mental health screening and preventive care",
      "Crisis intervention and emergency mental health support",
      "Wellness planning and long-term mental health maintenance",
    ],
  },
  {
    id: "Mood-Disorders",
    name: "Mood Disorders",
    id_sub: "Treatment for depression, bipolar disorder, and mood instability",
    title1: "Expert care for mood disorders and emotional regulation",
    title1Des:
      "Mood disorders affect how you feel emotionally and can significantly impact your daily life, relationships, and overall functioning. From depression to bipolar disorder, these conditions require specialized care and understanding. At Tinka Health, we provide comprehensive treatment for various mood disorders.",
    btnText: "Stabilize My Mood",
    title2: "Are mood swings or persistent sadness affecting your life?",
    title2Des:
      "Mood disorders can manifest in various ways and significantly impact your quality of life:",
    title2List: [
      "Persistent sadness, emptiness, or feelings of hopelessness",
      "Extreme mood swings between depression and mania or hypomania",
      "Loss of interest in activities you once enjoyed",
      "Changes in sleep, appetite, and energy levels",
      "Difficulty functioning at work, school, or in relationships",
      "Irritability, anger, or emotional outbursts",
      "Thoughts of self-harm or suicide",
    ],
    title3: "Tinka Health's Mood Disorder Treatment",
    title3Des:
      "Our comprehensive approach addresses the complex nature of mood disorders:",
    title3List: [
      "Accurate diagnosis and assessment of mood disorder symptoms",
      "Medication management and monitoring for mood stabilization",
      "Individual therapy using evidence-based approaches",
      "Family therapy and education about mood disorders",
      "Crisis intervention and safety planning",
      "Lifestyle interventions and wellness planning",
      "Long-term mood monitoring and relapse prevention",
    ],
  },
  {
    id: "Obsessive-Compulsive-Disorder",
    name: "Obsessive Compulsive Disorder",
    id_sub: "Break free from obsessions and compulsions",
    title1: "Overcome OCD with specialized treatment and support",
    title1Des:
      "Obsessive-Compulsive Disorder (OCD) involves unwanted, intrusive thoughts (obsessions) and repetitive behaviors or mental acts (compulsions) that you feel compelled to perform. OCD can be exhausting and interfere significantly with your daily life. At Tinka Health, we provide specialized treatment to help you break free from OCD cycles.",
    btnText: "Beat OCD",
    title2: "Is OCD controlling your daily life?",
    title2Des:
      "OCD can consume hours of your day and create significant distress. Common experiences include:",
    title2List: [
      "Intrusive, unwanted thoughts that cause anxiety and distress",
      "Repetitive behaviors or mental rituals you feel compelled to perform",
      "Time-consuming routines that interfere with daily activities",
      "Avoidance of situations that trigger obsessions",
      "Significant distress when unable to perform compulsions",
      "Impact on relationships, work, or school performance",
      "Feeling ashamed or embarrassed about your thoughts and behaviors",
    ],
    title3: "Tinka Health's Specialized OCD Treatment",
    title3Des:
      "Our evidence-based approach to OCD treatment helps you regain control of your life:",
    title3List: [
      "Exposure and Response Prevention (ERP) therapy - the gold standard for OCD treatment",
      "Cognitive Behavioral Therapy specifically adapted for OCD",
      "Medication management when appropriate",
      "Family education and support to reduce accommodation behaviors",
      "Gradual exposure exercises to reduce anxiety and compulsions",
      "Relapse prevention and long-term management strategies",
      "Support groups with others who understand OCD challenges",
    ],
  },
  {
    id: "Panic-Disorder",
    name: "Panic Disorder",
    id_sub: "Overcome panic attacks and regain control",
    title1: "Find relief from panic attacks with expert care",
    title1Des:
      "Panic disorder involves recurrent, unexpected panic attacks and persistent worry about having more attacks. These intense episodes of fear can make you feel like you're losing control or having a heart attack. At Tinka Health, we help you understand panic attacks, reduce their frequency, and regain confidence in your daily life.",
    btnText: "Stop Panic Attacks",
    title2: "Are panic attacks disrupting your life?",
    title2Des:
      "Panic attacks can be terrifying and lead to significant life changes as you try to avoid situations where they might occur:",
    title2List: [
      "Sudden, intense episodes of fear with physical symptoms like rapid heartbeat",
      "Fear of having another panic attack (anticipatory anxiety)",
      "Avoidance of places or situations where panic attacks have occurred",
      "Physical symptoms like sweating, trembling, shortness of breath, or dizziness",
      "Feeling like you're going crazy, losing control, or dying during attacks",
      "Emergency room visits due to panic attack symptoms",
      "Significant impact on work, social activities, or daily functioning",
    ],
    title3: "Tinka Health's Panic Disorder Treatment",
    title3Des:
      "Our comprehensive approach helps you overcome panic attacks and reduce anxiety:",
    title3List: [
      "Education about panic attacks and how they work in your body",
      "Breathing techniques and relaxation strategies for managing symptoms",
      "Cognitive therapy to address catastrophic thinking patterns",
      "Gradual exposure to feared situations in a safe, controlled way",
      "Medication management if appropriate",
      "Lifestyle changes to reduce overall anxiety and stress",
      "Long-term strategies for preventing future panic attacks",
    ],
  },
  {
    id: "Phobias",
    name: "Phobias",
    id_sub: "Overcome specific fears and phobias",
    title1: "Conquer your fears with specialized phobia treatment",
    title1Des:
      "Specific phobias involve intense, irrational fears of particular objects or situations that pose little or no actual danger. These fears can significantly limit your life and cause considerable distress. At Tinka Health, we use proven techniques to help you overcome phobias and reclaim your freedom.",
    btnText: "Face My Fears",
    title2: "Is a specific fear limiting your life?",
    title2Des:
      "Phobias can cause intense anxiety and lead to avoidance behaviors that restrict your daily activities:",
    title2List: [
      "Intense fear or anxiety when encountering the phobic object or situation",
      "Avoidance of situations that might involve your phobia",
      "Physical symptoms like rapid heartbeat, sweating, or trembling",
      "Recognition that your fear is excessive but feeling unable to control it",
      "Significant interference with work, social activities, or daily routines",
      "Anticipatory anxiety about potentially encountering your phobia",
      "Feeling embarrassed or ashamed about your fear",
    ],
    title3: "Tinka Health's Phobia Treatment Approach",
    title3Des:
      "Our evidence-based treatment helps you gradually overcome your phobia and reduce anxiety:",
    title3List: [
      "Systematic desensitization to gradually reduce fear responses",
      "Exposure therapy in a safe, controlled environment",
      "Cognitive restructuring to challenge irrational thoughts about your phobia",
      "Relaxation techniques and anxiety management strategies",
      "Virtual reality exposure therapy for certain phobias when appropriate",
      "Education about how phobias develop and are maintained",
      "Relapse prevention and confidence-building strategies",
    ],
  },
  {
    id: "Post-Traumatic-Stress-Disorder",
    name: "Post Traumatic Stress Disorder",
    id_sub: "Heal from trauma with specialized PTSD treatment",
    title1: "Recovery from trauma and PTSD with expert care",
    title1Des:
      "Post-Traumatic Stress Disorder (PTSD) can develop after experiencing or witnessing a traumatic event. It affects your ability to feel safe and can significantly impact your daily life, relationships, and well-being. At Tinka Health, we provide trauma-informed care to help you process your experiences and reclaim your life.",
    btnText: "Heal from Trauma",
    title2: "Are you struggling with the effects of trauma?",
    title2Des:
      "PTSD can develop after various traumatic experiences and significantly impact your life:",
    title2List: [
      "Intrusive memories, flashbacks, or nightmares about the traumatic event",
      "Avoidance of people, places, or situations that remind you of the trauma",
      "Negative changes in thoughts and mood, including feelings of hopelessness",
      "Hypervigilance and being easily startled or frightened",
      "Sleep problems, difficulty concentrating, or irritability",
      "Emotional numbness or detachment from loved ones",
      "Self-destructive behavior or substance use as coping mechanisms",
    ],
    title3: "Tinka Health's PTSD Treatment Approach",
    title3Des:
      "Our trauma-informed treatment helps you process traumatic experiences and develop healthy coping strategies:",
    title3List: [
      "Evidence-based therapies like EMDR, CPT, and Prolonged Exposure",
      "Individual trauma therapy in a safe, supportive environment",
      "Medication management for PTSD symptoms when appropriate",
      "Group therapy with other trauma survivors",
      "Family therapy to improve relationships and support systems",
      "Mindfulness and grounding techniques for managing triggers",
      "Long-term recovery planning and resilience building",
    ],
  },
  {
    id: "Persistent-feelings-of-sadness-emptiness-or-hopelessness",te to it.",
    btnText: "Start Recovery",
    title2: "Is addiction controlling your life and relationships?",
    title2Des:
      "Addiction often starts as a way to cope with pain, stress, or trauma, but it quickly becomes a cycle that's difficult to break. You might feel ashamed, isolated, or hopeless about your situation. Addiction doesn't just affect you - it impacts everyone who cares about you. Here's how addiction can take over your life:",
    title2List: [
      "Loss of control over your substance use or behaviors despite negative consequences",
      "Damaged relationships with family, friends, and romantic partners",
      "Problems at work or school, including decreased performance or attendance",
      "Financial difficulties due to spending money on substances or addictive behaviors",
      "Legal problems or risky behaviors that put you or others in danger",
      "Physical health complications and mental health issues like depression or anxiety",
      "Isolation and withdrawal from activities and people you once enjoyed",
      "Feelings of shame, guilt, and hopelessness about your ability to change",
    ],
    title3: "Tinka Health's goals for your recovery journey:",
    title3Des:
      "Recovery from addiction is a journey, not a destination. At Tinka Health, we believe that with the right support, anyone can overcome addiction and build a fulfilling life in recovery. We take a comprehensive approach that addresses the physical, emotional, and psychological aspects of addiction. Tinka Health will help you:",
    title3List: [
      "Develop a personalized treatment plan that addresses your specific addiction and underlying issues",
      "Learn healthy coping strategies to manage triggers, cravings, and stressful situations",
      "Address any co-occurring mental health conditions like depression, anxiety, or trauma",
      "Build a strong support network and repair damaged relationships when possible",
      "Understand the root causes of your addiction and develop insight into your patterns",
      "Create a relapse prevention plan and develop tools for long-term recovery",
      "Rebuild your life with purpose, meaning, and healthy habits that support your sobriety",
    ],
  },
  {
    id: "Adult-Psychiatry",
    name: "Adult Psychiatry",
    id_sub: "Comprehensive psychiatric care for adults",
    title1: "Expert psychiatric care tailored for adult mental health needs",
    title1Des:
      "Adult psychiatry focuses on the diagnosis, treatment, and prevention of mental health disorders in adults. At Tinka Health, our psychiatric services combine medication management with therapeutic support to provide comprehensive care that addresses both the biological and psychological aspects of mental health conditions.",
    btnText: "Get Psychiatric Care",
    title2: "Are you struggling with complex mental health challenges?",
    title2Des:
      "Many adults experience mental health conditions that require specialized psychiatric care. These conditions can significantly impact your daily life, relationships, and overall well-being. Without proper treatment, psychiatric conditions can lead to:",
    title2List: [
      "Persistent symptoms that interfere with work or personal relationships",
      "Difficulty managing emotions, thoughts, or behaviors",
      "Physical symptoms related to mental health conditions",
      "Increased risk of substance use or other harmful coping mechanisms",
      "Social isolation and withdrawal from important activities",
      "Decreased quality of life and overall functioning",
    ],
    title3: "How Tinka Health's Adult Psychiatry Services Help",
    title3Des:
      "Our adult psychiatry services provide comprehensive evaluation and treatment for a wide range of mental health conditions. Our experienced psychiatrists work closely with you to develop personalized treatment plans. Here's how we support your mental health:",
    title3List: [
      "Comprehensive psychiatric evaluations to accurately diagnose mental health conditions",
      "Medication management and monitoring to optimize treatment effectiveness",
      "Integration of therapy and medication for the best possible outcomes",
      "Treatment of complex conditions including bipolar disorder, schizophrenia, and severe depression",
      "Ongoing support and adjustment of treatment plans as needed",
      "Collaboration with other healthcare providers for holistic care",
      "Education about your condition and treatment options",
    ],
  },
  {
    id: "Agoraphobia",
    name: "Agoraphobia",
    id_sub: "Overcome fear of open spaces and regain your freedom",
    title1: "Conquer agoraphobia with expert guidance and support",
    title1Des:
      "Agoraphobia is more than just fear of open spaces - it's an anxiety disorder that can make you feel trapped in your own life. You might avoid places or situations where escape seems difficult or help unavailable. At Tinka Health, we understand how limiting agoraphobia can be, and we're here to help you gradually reclaim your independence and confidence.",
    btnText: "Reclaim My Freedom",
    title2: "Is agoraphobia limiting your life?",
    title2Des:
      "Agoraphobia can develop gradually or suddenly, often following a panic attack in a specific location. It can significantly impact your daily life and relationships, leading to:",
    title2List: [
      "Avoidance of crowded places, public transportation, or being alone outside",
      "Difficulty leaving your home or safe spaces",
      "Panic attacks when faced with feared situations",
      "Dependence on others for daily activities like shopping or errands",
      "Social isolation and strained relationships",
      "Impact on work or school attendance and performance",
      "Physical symptoms like rapid heartbeat, sweating, or dizziness",
    ],
    title3: "How Tinka Health Helps You Overcome Agoraphobia",
    title3Des:
      "Our approach to treating agoraphobia combines evidence-based techniques with gradual, supportive exposure. We'll work at your pace to help you:",
    title3List: [
      "Understand the connection between thoughts, feelings, and avoidance behaviors",
      "Learn relaxation and breathing techniques to manage panic and anxiety",
      "Gradually expose yourself to feared situations in a controlled, supportive way",
      "Challenge and change negative thoughts about safety and danger",
      "Develop coping strategies for managing anxiety in various situations",
      "Build confidence and independence in your daily activities",
      "Create a long-term plan for maintaining your progress",
    ],
  },
  {
    id: "Alzheimers-Disease",
    name: "Alzheimer's Disease",
    id_sub: "Support for patients and families facing cognitive decline",
    title1: "Comprehensive care for Alzheimer's disease and dementia",
    title1Des:
      "Alzheimer's disease affects not just the individual diagnosed, but their entire family and support network. At Tinka Health, we provide compassionate care and support for both patients in early stages and their families, helping navigate the emotional, practical, and psychological challenges of this condition.",
    btnText: "Get Support",
    title2: "Are you or your loved one facing Alzheimer's challenges?",
    title2Des:
      "Alzheimer's disease brings unique challenges that can feel overwhelming. Early intervention and support can make a significant difference in quality of life for everyone involved:",
    title2List: [
      "Memory loss and confusion that interferes with daily activities",
      "Changes in mood, personality, or behavior",
      "Difficulty with problem-solving and decision-making",
      "Challenges with communication and language",
      "Family stress and caregiver burnout",
      "Anxiety and depression related to the diagnosis",
      "Planning for future care needs and legal matters",
    ],
    title3: "Tinka Health's Approach to Alzheimer's Support",
    title3Des:
      "We provide comprehensive support that addresses the psychological and emotional aspects of Alzheimer's disease for both patients and families:",
    title3List: [
      "Individual counseling for patients dealing with diagnosis and early-stage symptoms",
      "Family therapy to improve communication and coping strategies",
      "Support groups for caregivers and family members",
      "Grief counseling for the losses associated with cognitive decline",
      "Stress management techniques for caregivers",
      "Coordination with healthcare providers for comprehensive care",
      "Resources and education about the disease and available support services",
    ],
  },
  {
    id: "Anger-Management",
    name: "Anger Management",
    id_sub: "Learn healthy ways to express and control anger",
    title1: "Transform your relationship with anger through professional guidance",
    title1Des:
      "Anger is a natural emotion, but when it becomes overwhelming or destructive, it can damage relationships and negatively impact your life. Tinka Health's anger management services help you understand your triggers, develop healthy coping strategies, and learn to express anger in constructive ways.",
    btnText: "Manage My Anger",
    title2: "Is anger causing problems in your life?",
    title2Des:
      "Uncontrolled anger can have serious consequences for your relationships, career, and overall well-being. Many people struggle with anger management, and without proper support, it can lead to:",
    title2List: [
      "Damaged relationships with family, friends, and colleagues",
      "Problems at work or school, including potential job loss",
      "Legal issues or conflicts that could have been avoided",
      "Physical health problems related to chronic stress and anger",
      "Feelings of guilt, shame, and regret after angry outbursts",
      "Social isolation and loss of important relationships",
    ],
    title3: "Tinka Health's Approach to Anger Management",
    title3Des:
      "Our anger management program is designed to help you gain control over your anger responses and develop healthier ways to cope with frustration and stress. Through evidence-based techniques, you'll learn to:",
    title3List: [
      "Identify your anger triggers and early warning signs",
      "Develop better communication skills to express your needs without aggression",
      "Practice conflict resolution strategies that protect your relationships",
      "Build emotional regulation skills that help you stay calm under pressure",
      "Address any underlying mental health conditions that might contribute to anger issues",
    ],
  },
  {
    id: "Antidepressants",
    name: "Antidepressants",
    id_sub: "Expert medication management and monitoring",
    title1: "Professional antidepressant medication management",
    title1Des:
      "Finding the right antidepressant medication can be a crucial part of your mental health treatment. At Tinka Health, our psychiatric professionals provide expert medication management, ensuring you receive the most effective treatment with minimal side effects, while monitoring your progress closely.",
    btnText: "Get Medication Support",
    title2: "Are you considering or currently taking antidepressants?",
    title2Des:
      "Antidepressant medication can be highly effective, but finding the right medication and dosage requires professional guidance and ongoing monitoring:",
    title2List: [
      "Uncertainty about which medication might work best for you",
      "Concerns about side effects or interactions with other medications",
      "Questions about how long treatment should continue",
      "Need for dosage adjustments or medication changes",
      "Monitoring for effectiveness and side effects",
      "Support during the initial weeks when medications are taking effect",
    ],
    title3: "Tinka Health's Medication Management Approach",
    title3Des:
      "Our comprehensive medication management ensures you receive safe, effective treatment tailored to your specific needs:",
    title3List: [
      "Thorough psychiatric evaluation to determine the best medication options",
      "Regular monitoring appointments to assess effectiveness and side effects",
      "Gradual dosage adjustments based on your response and tolerance",
      "Education about your medication, including benefits and potential side effects",
      "Coordination with your primary care physician and other healthcare providers",
      "Support during medication transitions or discontinuation when appropriate",
      "Integration of medication management with therapy for optimal outcomes",
    ],
  },
  {
    id: "Anxiety",
    name: "Anxiety",
    id_sub: "Find relief from worry, fear, and anxious thoughts",
    title1: "Overcome anxiety with personalized treatment and support",
    title1Des:
      "Anxiety is one of the most common mental health challenges, affecting millions of people. Whether you're dealing with general worry, specific fears, or physical symptoms of anxiety, Tinka Health provides comprehensive treatment to help you find relief and regain control of your life.",
    btnText: "Get Anxiety Relief",
    title2: "Is anxiety affecting your daily life?",
    title2Des:
      "Anxiety can manifest in many different ways and impact every aspect of your life. Common signs and effects include:",
    title2List: [
      "Persistent worry about everyday situations",
      "Physical symptoms like rapid heartbeat, sweating, or trembling",
      "Difficulty concentrating or making decisions",
      "Sleep problems or restlessness",
      "Avoidance of situations that trigger anxiety",
      "Fatigue from constant worry and tension",
      "Impact on relationships, work, or school performance",
    ],
    title3: "How Tinka Health Treats Anxiety",
    title3Des:
      "Our approach to anxiety treatment is comprehensive and personalized, using evidence-based techniques to help you:",
    title3List: [
      "Identify and understand your specific anxiety triggers",
      "Learn practical coping strategies and relaxation techniques",
      "Challenge and change anxious thought patterns",
      "Gradually face feared situations in a safe, controlled way",
      "Develop long-term strategies for managing anxiety",
      "Address any underlying issues contributing to your anxiety",
      "Build confidence and resilience for lasting recovery",
    ],
  },
  {
    id: "Anxiety-Disorders",
    name: "Anxiety Disorders",
    id_sub: "Find relief from overwhelming anxiety and worry",
    title1: "Overcome anxiety with expert care and support",
    title1Des:
      "Anxiety disorders are among the most common mental health conditions, affecting millions of people. If you're struggling with persistent worry, fear, or panic, you're not alone. Tinka Health offers comprehensive treatment for various anxiety disorders, helping you regain control of your life and find lasting relief.",
    btnText: "Get Relief Now",
    title2: "Is anxiety controlling your life?",
    title2Des:
      "Anxiety can manifest in many ways and significantly impact your daily functioning. Whether you're experiencing generalized anxiety, panic attacks, social anxiety, or specific phobias, untreated anxiety can lead to:",
    title2List: [
      "Persistent worry and fear that interferes with daily activities",
      "Physical symptoms like rapid heartbeat, sweating, or difficulty breathing",
      "Avoidance of situations, people, or places that trigger anxiety",
      "Sleep disturbances and chronic fatigue",
      "Difficulty concentrating at work or school",
      "Strained relationships due to anxiety-related behaviors",
      "Development of depression or other mental health conditions",
    ],
    title3: "How Tinka Health Helps You Overcome Anxiety",
    title3Des:
      "Our comprehensive approach to treating anxiety disorders combines evidence-based therapies with personalized care. We'll work together to understand your specific anxiety triggers and develop effective coping strategies. Here's how we support your recovery:",
    title3List: [
      "Identify and challenge negative thought patterns that fuel anxiety",
      "Learn practical relaxation and breathing techniques for immediate relief",
      "Develop gradual exposure strategies to overcome specific fears and phobias",
      "Build confidence and resilience through behavioral interventions",
      "Address any underlying trauma or life stressors contributing to anxiety",
      "Create a personalized toolkit of coping strategies for long-term management",
    ],
  },
  {
    id: "Attention-Deficit-Hyperactivity-Disorder",
    name: "Attention Deficit Hyperactivity Disorder",
    id_sub: "Comprehensive ADHD evaluation and treatment",
    title1: "Expert ADHD diagnosis and management for all ages",
    title1Des:
      "ADHD affects millions of children and adults, impacting focus, impulse control, and daily functioning. At Tinka Health, we provide comprehensive ADHD evaluations, accurate diagnosis, and personalized treatment plans that may include therapy, medication management, and behavioral strategies to help you or your loved one thrive.",
    btnText: "Get ADHD Support",
    title2: "Is ADHD affecting your or your child's life?",
    title2Des:
      "ADHD symptoms can significantly impact academic, work, and social functioning. Common challenges include:",
    title2List: [
      "Difficulty focusing on tasks or following through on responsibilities",
      "Impulsive behavior that leads to problems at school, work, or in relationships",
      "Hyperactivity or restlessness that interferes with daily activities",
      "Problems with organization, time management, and planning",
      "Academic or work performance below potential",
      "Social difficulties and strained relationships",
      "Low self-esteem and frustration with ongoing challenges",
    ],
    title3: "Tinka Health's Comprehensive ADHD Treatment",
    title3Des:
      "Our approach to ADHD treatment is thorough and individualized, designed to help you or your child succeed:",
    title3List: [
      "Comprehensive evaluation and accurate diagnosis of ADHD",
      "Medication management with careful monitoring and adjustments",
      "Behavioral therapy and coaching to develop coping strategies",
      "Family education and support to improve home and school environments",
      "Coordination with schools and teachers for academic accommodations",
      "Social skills training and peer relationship support",
      "Long-term planning for academic and career success",
    ],
  },
  {
    id: "Autism-Spectrum-Disorder",
    name: "Autism Spectrum Disorder",
    id_sub: "Support for individuals and families navigating autism",
    title1: "Comprehensive autism spectrum disorder support and services",
    title1Des:
      "Autism Spectrum Disorder (ASD) affects individuals differently, but all deserve understanding, support, and the opportunity to reach their full potential. At Tinka Health, we provide specialized services for individuals with autism and their families, focusing on building strengths, addressing challenges, and improving quality of life.",
    btnText: "Get Autism Support",
    title2: "Are you seeking support for autism spectrum challenges?",
    title2Des:
      "Autism spectrum disorder can present various challenges that affect daily life, relationships, and development:",
    title2List: [
      "Difficulty with social communication and interaction",
      "Repetitive behaviors or intense interests in specific topics",
      "Challenges with transitions and changes in routine",
      "Sensory sensitivities that affect daily activities",
      "Academic or workplace accommodations needs",
      "Family stress and need for support and resources",
      "Building independence and life skills",
    ],
    title3: "How Tinka Health Supports Individuals with Autism",
    title3Des:
      "Our autism support services are designed to meet the unique needs of each individual and their family:",
    title3List: [
      "Comprehensive autism evaluations and diagnosis",
      "Individual therapy focused on social skills and communication",
      "Family support and education about autism spectrum disorders",
      "Behavioral interventions to address challenging behaviors",
      "Social skills groups and peer interaction opportunities",
      "Coordination with schools and other service providers",
      "Transition planning for adolescents and young adults",
    ],
  },
  {
    id: "Bereavement",
    name: "Bereavement",
    id_sub: "Compassionate support through loss and grief",
    title1: "Healing support for those experiencing loss and grief",
    title1Des:
      "Losing someone important to you is one of life's most difficult experiences. Grief is a natural response to loss, but it can feel overwhelming and isolating. At Tinka Health, we provide compassionate bereavement counseling to help you navigate your grief journey and find ways to honor your loved one while rebuilding your life.",
    btnText: "Find Grief Support",
    title2: "Are you struggling with the pain of loss?",
    title2Des:
      "Grief affects everyone differently and can impact all aspects of your life. Common experiences include:",
    title2List: [
      "Overwhelming sadness, anger, or numbness",
      "Difficulty accepting the reality of the loss",
      "Physical symptoms like fatigue, sleep problems, or loss of appetite",
      "Trouble concentrating on daily tasks or making decisions",
      "Feeling disconnected from others or socially isolated",
      "Guilt or regret about things said or left unsaid",
      "Difficulty finding meaning or purpose after the loss",
    ],
    title3: "Tinka Health's Approach to Bereavement Support",
    title3Des:
      "Our bereavement counseling provides a safe space to process your grief and begin healing:",
    title3List: [
      "Individual counseling to process your unique grief experience",
      "Support groups with others who have experienced similar losses",
      "Help understanding the grief process and what to expect",
      "Coping strategies for managing difficult emotions and memories",
      "Guidance on how to maintain connections with your deceased loved one",
      "Support for family members and loved ones also affected by the loss",
      "Assistance with anniversary dates, holidays, and other difficult times",
    ],
  },
  {
    id: "Bipolar-Disorder",
    name: "Bipolar Disorder",
    id_sub: "Manage mood swings and live with stability",
    title1: "Get support for managing bipolar disorder with Tinka Health",
    title1Des:
      "If you are living with bipolar disorder, you might feel like a slave to your moods and emotions. At some points, you feel depressed, unmotivated, and withdrawn. However, at other times, you feel elated, impulsive, restless, agitated, and full of self-confidence. This emotional instability can greatly impact your life but Tinka Health is here to help you stabilize your moods and make healthier choices.",
    btnText: "Let's Do It",
    title2: "Does bipolar disorder make your moods unpredictable?",
    title2Des:
      "Bipolar disorder is characterized by mood swings between hypomania, mania, and major depressive episodes, with types ranging from Bipolar I (severe mania sometimes requiring hospitalization) to Bipolar II (major depressive episodes with less severe hypomania) and cyclothymia (frequent, less intense mood shifts). Manic episodes may bring heightened energy, irritability, and impulsive behaviors like overspending or risk-taking, which, despite the temporary high, often lead to serious consequences including:",
    title2List: [
      "Emotional crashes after manic episodes",
      "Impulsive actions that might result in harm or regret",
      "Substance use as a coping mechanism",
      "Struggles with relationships",
      "Fluctuations in sleep, appetite, and energy",
      "Poor self-image or identity crises",
    ],
    title3: "Tinka Health's approach to therapy for bipolar disorder",
    title3Des:
      "Bipolar disorder affects everyone differently, and Tinka Health understands that your experience is unique. Our goal is to help you regulate your mood and regain control of your mental health. Here's how Tinka Health can support you:",
    title3List: [
      "Explore treatment options, including lifestyle changes, talk therapy, and potentially medication, to help you manage mood swings.",
      "Reduce impulsive or risky behaviors that could impact your relationships, health, finances, or work.",
      "Address depressive feelings, social withdrawal, and thoughts of self-harm.",
      "Decrease substance use during mood episodes and find healthier coping mechanisms.",
      "Understand how bipolar disorder affects your life and develop strategies to navigate periods of mania and depression effectively.",
    ],
  },
  {
    id: "Child-Behavior-Disorders",
    name: "Child Behavior Disorders",
    id_sub: "Professional support for challenging childhood behaviors",
    title1: "Expert care for child behavior disorders and family support",
    title1Des:
      "Child behavior disorders can be challenging for both children and their families. These conditions affect a child's ability to regulate emotions and behaviors, impacting their relationships, school performance, and family life. At Tinka Health, we provide comprehensive assessment and treatment for various childhood behavior disorders.",
    btnText: "Get Child Support",
    title2: "Is your child struggling with behavioral challenges?",
    title2Des:
      "Child behavior disorders can manifest in various ways and significantly impact family life and your child's development:",
    title2List: [
      "Frequent temper tantrums or aggressive outbursts",
      "Defiant behavior and difficulty following rules or instructions",
      "Problems at school with teachers and peers",
      "Difficulty regulating emotions and impulses",
      "Social problems and trouble making or keeping friends",
      "Family stress and conflict over behavioral issues",
      "Academic performance below potential",
    ],
    title3: "Tinka Health's Approach to Child Behavior Disorders",
    title3Des:
      "Our comprehensive treatment approach addresses both the child's needs and supports the entire family:",
    title3List: [
      "Thorough assessment to identify specific behavioral challenges and underlying causes",
      "Individual therapy for children using age-appropriate techniques",
      "Parent training and family therapy to improve home environment",
      "Behavioral interventions and positive reinforcement strategies",
      "Coordination with schools for consistent behavioral support",
      "Social skills training to improve peer relationships",
      "Long-term planning for continued behavioral success",
    ],
  },
  {
    id: "Child-Mental-Health",
    name: "Child Mental Health",
    id_sub: "Comprehensive mental health care for children and adolescents",
    title1: "Expert mental health support for children and teens",
    title1Des:
      "Children and adolescents can experience a wide range of mental health challenges that require specialized care. At Tinka Health, we provide age-appropriate mental health services designed specifically for young people, using evidence-based treatments that support healthy development and emotional well-being.",
    btnText: "Support My Child",
    title2: "Is your child struggling with mental health challenges?",
    title2Des:
      "Mental health issues in children and adolescents can affect their emotional, social, and academic development:",
    title2List: [
      "Changes in mood, behavior, or personality",
      "Declining academic performance or school avoidance",
      "Social withdrawal and difficulty with peer relationships",
      "Sleep problems, nightmares, or changes in appetite",
      "Excessive worry, fear, or anxious behaviors",
      "Attention and concentration difficulties",
      "Aggressive or self-destructive behaviors",
    ],
    title3: "Tinka Health's Child Mental Health Services",
    title3Des:
      "Our specialized approach to child mental health provides comprehensive care for young people:",
    title3List: [
      "Age-appropriate assessment and diagnosis of mental health conditions",
      "Individual therapy using play therapy, art therapy, and talk therapy techniques",
      "Family therapy to improve communication and support systems",
      "Group therapy and social skills development",
      "Coordination with schools and pediatricians for comprehensive care",
      "Parent education and support for managing mental health challenges",
      "Crisis intervention and safety planning when needed",
    ],
  },
  {
    id: "Coping-with-Chronic-Illness",
    name: "Coping with Chronic Illness",
    id_sub: "Mental health support for chronic medical conditions",
    title1: "Navigate the emotional challenges of chronic illness",
    title1Des:
      "Living with a chronic illness can be emotionally overwhelming and impact every aspect of your life. Beyond the physical symptoms, chronic conditions often bring anxiety, depression, grief, and lifestyle changes that require psychological support. At Tinka Health, we help you develop coping strategies and maintain mental wellness while managing your medical condition.",
    btnText: "Get Coping Support",
    title2: "Are you struggling emotionally with chronic illness?",
    title2Des:
      "Chronic illness affects not just your physical health, but your emotional and mental well-being as well:",
    title2List: [
      "Anxiety and worry about your condition and prognosis",
      "Depression related to lifestyle changes and limitations",
      "Grief over the loss of your previous health and abilities",
      "Stress from managing complex medical treatments",
      "Relationship changes and social isolation",
      "Financial concerns related to medical costs and work limitations",
      "Difficulty adjusting to a new sense of identity and future plans",
    ],
    title3: "How Tinka Health Supports Those with Chronic Illness",
    title3Des:
      "Our approach addresses the unique psychological challenges of living with chronic medical conditions:",
    title3List: [
      "Individual counseling to process emotions related to your diagnosis",
      "Coping strategies for managing pain, fatigue, and other symptoms",
      "Support for lifestyle adjustments and maintaining quality of life",
      "Techniques for managing medical anxiety and treatment-related stress",
      "Family counseling to help loved ones understand and support you",
      "Coordination with your medical team for comprehensive care",
      "Support groups with others facing similar health challenges",
    ],
  },
  {
    id: "Coping-with-Disasters",
    name: "Coping with Disasters",
    id_sub: "Mental health support after traumatic events and disasters",
    title1: "Recovery and resilience after disasters and traumatic events",
    title1Des:
      "Natural disasters, accidents, and other traumatic events can have lasting psychological effects on individuals and communities. These experiences can lead to anxiety, depression, PTSD, and other mental health challenges. At Tinka Health, we provide specialized support to help you process trauma and rebuild your sense of safety and stability.",
    btnText: "Get Trauma Support",
    title2: "Are you struggling after a disaster or traumatic event?",
    title2Des:
      "Disasters and traumatic events can have profound psychological effects that may persist long after the immediate danger has passed:",
    title2List: [
      "Intrusive memories, flashbacks, or nightmares about the event",
      "Anxiety and hypervigilance about potential future dangers",
      "Depression and feelings of hopelessness about the future",
      "Difficulty sleeping or concentrating on daily tasks",
      "Avoidance of places or situations that remind you of the trauma",
      "Survivor guilt or questioning why you were spared",
      "Relationship problems and social withdrawal",
    ],
    title3: "Tinka Health's Disaster Recovery Support",
    title3Des:
      "Our trauma-informed approach helps individuals and families recover from disasters and traumatic events:",
    title3List: [
      "Individual trauma therapy using evidence-based treatments",
      "Family therapy to address collective trauma and support healing",
      "Community support groups for disaster survivors",
      "Crisis intervention and immediate mental health support",
      "Coping strategies for managing trauma symptoms and triggers",
      "Resilience building and post-traumatic growth work",
      "Coordination with emergency services and community resources",
    ],
  },
  {
    id: "Delirium",
    name: "Delirium",
    id_sub: "Support for confusion and cognitive changes",
    title1: "Understanding and managing delirium with professional care",
    title1Des:
      "Delirium is a serious condition characterized by rapid changes in mental function, including confusion, disorientation, and altered consciousness. It can be frightening for both patients and families. At Tinka Health, we provide support and education to help understand delirium, its causes, and strategies for management and recovery.",
    btnText: "Get Delirium Support",
    title2: "Are you or your loved one experiencing delirium?",
    title2Des:
      "Delirium can develop quickly and cause significant distress for patients and their families:",
    title2List: [
      "Rapid onset of confusion and disorientation",
      "Fluctuating levels of consciousness and attention",
      "Memory problems and difficulty recognizing familiar people or places",
      "Agitation, restlessness, or unusual behaviors",
      "Sleep disturbances and day-night confusion",
      "Hallucinations or delusions",
      "Family distress and difficulty understanding the condition",
    ],
    title3: "Tinka Health's Approach to Delirium Support",
    title3Des:
      "Our comprehensive approach addresses both the psychological and practical aspects of delirium:",
    title3List: [
      "Education for patients and families about delirium and its causes",
      "Individual counseling for those recovering from delirium episodes",
      "Family support and guidance for managing delirium at home",
      "Coping strategies for dealing with confusion and memory problems",
      "Coordination with medical providers for comprehensive care",
      "Support for preventing future episodes when possible",
      "Grief counseling for losses associated with cognitive changes",
    ],
  },
  {
    id: "Dementia",
    name: "Dementia",
    id_sub: "Comprehensive support for dementia patients and families",
    title1: "Compassionate care for dementia and cognitive decline",
    title1Des:
      "Dementia affects not only the person diagnosed but their entire support network. The progressive nature of cognitive decline brings unique challenges that require specialized understanding and support. At Tinka Health, we provide comprehensive care for individuals with dementia and their families throughout the journey.",
    btnText: "Get Dementia Support",
    title2: "Are you or your loved one facing dementia challenges?",
    title2Des:
      "Dementia brings complex challenges that evolve over time and affect everyone involved:",
    title2List: [
      "Progressive memory loss and cognitive decline",
      "Changes in personality, mood, and behavior",
      "Difficulty with daily activities and independence",
      "Communication challenges and social withdrawal",
      "Caregiver stress and burnout",
      "Family grief and adjustment to changing relationships",
      "Planning for future care needs and safety concerns",
    ],
    title3: "Tinka Health's Comprehensive Dementia Support",
    title3Des:
      "Our approach provides support for all stages of dementia and addresses the needs of patients and families:",
    title3List: [
      "Early-stage counseling for individuals adjusting to diagnosis",
      "Family education and support throughout the dementia journey",
      "Caregiver support groups and stress management",
      "Behavioral interventions for challenging dementia-related behaviors",
      "Grief counseling for losses associated with cognitive decline",
      "Care planning and coordination with healthcare providers",
      "End-of-life support and bereavement counseling",
    ],
  },
  {
    id: "Depression",
    name: "Depression",
    id_sub: "Find hope and healing from depression",
    title1: "Overcome depression with compassionate, professional support",
    title1Des:
      "Depression is more than just feeling sad or going through a rough patch. It's a serious mental health condition that affects how you think, feel, and handle daily activities. At Tinka Health, we understand that depression can feel overwhelming and isolating, but with the right support and treatment, recovery is possible.",
    btnText: "Start Healing",
    title2: "Is depression affecting your daily life?",
    title2Des:
      "Depression can manifest in various ways and significantly impact every aspect of your life. If you're experiencing persistent sadness, loss of interest in activities, or other symptoms of depression, you may be dealing with:",
    title2List: [
      "Persistent feelings of sadness, emptiness, or hopelessness",
      "Loss of interest or pleasure in activities you once enjoyed",
      "Significant changes in appetite or weight",
      "Sleep disturbances, including insomnia or oversleeping",
      "Fatigue and decreased energy levels",
      "Difficulty concentrating, making decisions, or remembering things",
      "Feelings of worthlessness or excessive guilt",
      "Thoughts of death or suicide",
    ],
    title3: "How Tinka Health Helps You Overcome Depression",
    title3Des:
      "Our approach to treating depression is comprehensive and personalized, combining evidence-based therapies with compassionate support. We'll work together to understand the root causes of your depression and develop effective strategies for healing. Here's how we support your recovery:",
    title3List: [
      "Identify and challenge negative thought patterns that contribute to depression",
      "Develop healthy coping strategies for managing difficult emotions",
      "Address any underlying trauma or life stressors that may be contributing to your depression",
      "Build a support network and improve your relationships",
      "Establish healthy routines and lifestyle habits that support mental wellness",
      "Work on building self-esteem and rediscovering your sense of purpose",
      "Create a personalized relapse prevention plan for long-term recovery",
    ],
  },
  {
    id: "Dual-Diagnosis",
    name: "Dual Diagnosis",
    id_sub: "Integrated treatment for co-occurring mental health and substance use disorders",
    title1: "Comprehensive care for dual diagnosis conditions",
    title1Des:
      "Dual diagnosis refers to the co-occurrence of mental health disorders and substance use disorders. These conditions often reinforce each other, making treatment more complex but not impossible. At Tinka Health, we provide integrated treatment that addresses both conditions simultaneously for the best possible outcomes.",
    btnText: "Get Dual Diagnosis Help",
    title2: "Are you struggling with both mental health and substance use issues?",
    title2Des:
      "Dual diagnosis conditions present unique challenges that require specialized treatment approaches:",
    title2List: [
      "Using substances to self-medicate mental health symptoms",
      "Mental health symptoms worsened by substance use",
      "Difficulty determining which condition to treat first",
      "Higher risk of relapse without integrated treatment",
      "Complex medication interactions and management needs",
      "Social and relationship problems related to both conditions",
      "Legal, financial, or work problems from substance use",
    ],
    title3: "Tinka Health's Integrated Dual Diagnosis Treatment",
    title3Des:
      "Our comprehensive approach treats both mental health and substance use disorders simultaneously:",
    title3List: [
      "Comprehensive assessment of both mental health and substance use patterns",
      "Integrated treatment planning that addresses both conditions",
      "Individual therapy focusing on recovery from both disorders",
      "Medication management considering interactions between treatments",
      "Group therapy with others facing similar dual diagnosis challenges",
      "Family education and support for understanding both conditions",
      "Relapse prevention planning for sustained recovery from both disorders",
    ],
  },
];

export default servicesDataList;
